# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "kaathepython/telebot"
  tag: "v1.1.0-e763606"
  os: "linux"
  arch: "amd64"
# Додатково визначте секцію для токену TELE_TOKEN
secret:
  name: "telebot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
